---
title: "DE-Hai"
author: "Patricia Gribi"
date: "2024-08-05"
output: html_document
---


Lat, Long:	51.0792, 10.4522

CMIP6 data: lat 51.4, 10



# Reading CMIP6 data

```{r}

library(ncdf4)
library(dplyr)
library(tidyr)
library(ggplot2)
library(lubridate)
library(tidyverse)


# data reading

## evapotranspiration (kg m-2 s-1)
evspsbl_CMIP6ng_data <- nc_open("/data_1/CMIP6/data_download/cmip6-ng/evspsbl/mon/native/evspsbl_mon_CESM2_ssp585_r1i1p1f1_native.nc") 

## precipitation (kg m-2 s-1)
pr_CMIP6ng_data <- nc_open("/data_1/CMIP6/data_download/cmip6-ng/pr/day/native/pr_day_CESM2_ssp585_r1i1p1f1_native.nc")


# gridpoint extraction
gridpoint_extraction <- function(data, variable, longitude= 10.4522, latitude=51.0792) {

  # indices of the grid point
  start_lon <- longitude
  start_lat <- latitude


  # get days
  var_dates <- as.Date(data$dim$time$vals, origin = '1850-01-01')

  # get values at location lon lat
  var_output <- ncvar_get(data, varid = variable,
                          start= c(which.min(abs(data$dim$lon$vals - start_lon)), # closest lon taken
                                   which.min(abs(data$dim$lat$vals - start_lat)),  # closest lat taken
                                   1),
                          # specifies number of elements to be retrieved along each dimension.
                          count = c(1,1,-1))  # 1: one element retrieved along lat and lon dim (single grid cell), -1: all available time steps retrieved.

  # create dataframe
  var <- data.frame(dates= var_dates, variable = var_output)

  return(var)
}

df_evap <- gridpoint_extraction(evspsbl_CMIP6ng_data, "evspsbl") # lon=116.25, lat=-21.2)
df_prec <- gridpoint_extraction(pr_CMIP6ng_data, "pr") # lon=116.25, lat=-21.2)


# resolution adjustments
## extract year and month from the dates column
df_prec <- df_prec |>
    mutate(year = lubridate::year(dates), month = lubridate::month(dates))|>
    rename(pr = variable)

df_evap <- df_evap |>
    mutate(year = lubridate::year(dates), month = lubridate::month(dates))|>
    select(-dates) |>
    rename(evspsbl = variable)

## merge all such that monthly data is repeated for each day within month
df_cwd <- df_prec |>
  left_join(df_evap, by = join_by(year, month)) |>
  dplyr::select(-year, -month)


# unit conversions
## evapotranspiration
df_cwd$evspsbl <- df_cwd$evspsbl * 86400 # conversion to mm day-1

## precipitation
df_cwd$pr <- df_cwd$pr * 86400 # conversion to mm day-1

```


## Annual totals of evapotranspiration and precipitation

```{r, warning=FALSE}

ann_df_cwd <- df_cwd |>
  mutate(year = year(dates)) |>
  group_by(year) |>
  summarise(et = sum(evspsbl), prec = sum(pr))



ann_df_cwd |>
  pivot_longer(cols = c(et, prec), names_to = "Flux") |> 
  ggplot(aes(x = year, y = value, color = Flux)) +
  geom_line() +
  ggtitle("Annual totals of et and prec")+
  labs(y = "Flux (mm/yr)")

```




