---
title: "EVA_Regional_Duration"
author: "Patricia Helpap"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r libraries, message=FALSE, echo=FALSE}
library(readr)
library(dplyr)
library(here)
library(lubridate)
library(patchwork)
library(extRemes)
library(ggplot2)
library(cwd)
library(ncdf4)
library(reshape2)
library(ggpubr)
library(maps)
library(raster)
library(rnaturalearth)
library(sf)
library(rgdal)
library(sp)
library(RColorBrewer)
library(rJava)
library(loadeR.java)
library(transformeR)
library(loadeR)
library(visualizeR)
library(geoprocessoR)
library(tidyverse)
library(abind)
library(patchwork)
library(gridExtra)
```

# Extreme Value Analysis of Drought Duration 

```{r regions setup, echo=FALSE, warning=FALSE, message=FALSE}
#Load reference regions and coastlines:

load("/storage/homefs/ph23v078/Reference_regions/IPCC-WGI-reference-regions-v4_R.rda", verbose = TRUE)

#simplify this object by converting it to a SpatialPolygons class object (i.e., only the polygons are retained and their attributes discarded):
refregions <- as(IPCC_WGI_reference_regions_v4, "SpatialPolygons")

temp.dir <- tempdir()
unzip("/storage/homefs/ph23v078/Reference_regions/ne_110m_coastline.zip", exdir = temp.dir)
coastLines <- readOGR(dsn = temp.dir, layer = "ne_110m_coastline")

names(names(refregions))

proj4string(refregions)
WCE <- refregions[c("WCE")]

```

```{r map of regions, echo=FALSE, warning=FALSE, message=FALSE}
# Convert `refregions` (SpatialPolygons) to an `sf` object for ggplot compatibility
refregions_sf <- st_as_sf(refregions)

# Define continent assignments
continent_mapping <- list(
  "Europe" = c("NEU", "WCE", "EEU", "MED"),
  "North America" = c("NWN", "NEN", "WNA", "CNA", "ENA", "GIC"),
  "Africa" = c("SAH", "WAF", "CAF", "NEAF", "SEAF", "WSAF", "ESAF", "MDG"),
  "Asia" = c("WCA", "ECA", "TIB", "EAS", "ARP", "SAS", "SEA", "WSB", "ESB", "RFE", "RAR"),
  "Central America" =c("NCA", "SCA", "CAR"),
  "South America" = c("NWS", "NSA", "NES", "SAM", "SWS", "SES", "SSA"),
  "Australia" = c("NAU", "CAU", "EAU", "SAU", "NZ")
)

# Assign continents to regions
refregions_sf <- refregions_sf %>%
  mutate(
    continent = case_when(
      row.names(refregions) %in% continent_mapping$Europe ~ "Europe",
      row.names(refregions) %in% continent_mapping$`North America` ~ "North America",
      row.names(refregions) %in% continent_mapping$Africa ~ "Africa",
      row.names(refregions) %in% continent_mapping$Asia ~ "Asia",
      row.names(refregions) %in% continent_mapping$`Central America` ~ "Central America",
      row.names(refregions) %in% continent_mapping$`South America` ~ "South America",
      row.names(refregions) %in% continent_mapping$Australia ~ "Australia",
      TRUE ~ "Other"  # For regions not mapped to a continent
    )
  ) 


# Define continent colors
continent_colors <- c(
  "Europe" = "pink",
  "North America" = "lightgreen",
  "Africa" = "purple",
  "Asia" = "orange",
  "Central America" = "lightblue",
  "South America" = "yellow",
  "Australia" = "blue",
  "Other" = "white"
)

# Extract region centroids for labeling
region_labels <- refregions_sf %>%
  st_centroid() %>%
  mutate(label = row.names(refregions))  # Add region names as labels


# Load land data for filling continents
land <- ne_countries(scale = "medium", returnclass = "sf")
```

```{r read in EMs WCE only, echo=FALSE, message=FALSE, warning=FALSE}
#here reading in only for WCE region for development
#aggregate EM for region i.e. 2 for loops, 1 looping over EMs, second looping over region, aggregating into one file

###############################read in data##################################
path <- "/storage/research/giub_geco/data_2/scratch/phelpap/ModESim"
folders <- list.files(path, full.names = TRUE, pattern = "m[0-9]{3}_tidy")

# Identify the target files
target_files <- file.path(folders, "02_2_pcwd_result_1850/PCWD_maxlen.nc")
target_files <- target_files[file.exists(target_files)]


#################################all EMS#######################################
#e.g. loop for EMs: ### append data i.e. get rid of time dimension and just append to exisiting data
# Extract unique ensemble member identifiers from folder names
ensemble_members <- unique(basename(folders))

# Initialize an empty list to store spatial averages for each file
spatial_avg_list <- list()

# Loop over all ensemble member folders
for (em in ensemble_members) {
  # Construct the folder path for the current ensemble member
  folder <- file.path(path, em)
  # Construct file paths for the two time periods
  file_1420 <- file.path(folder, "02_2_pcwd_result_1420/PCWD_maxlen.nc")
  file_1850 <- file.path(folder, "02_2_pcwd_result_1850/PCWD_maxlen.nc")
  
  # Check if both files exist
  if (file.exists(file_1420) && file.exists(file_1850)) {
    # Load grid data for each time period
    grid_1420 <- loadGridData(dataset = file_1420, var = "pcwd_maxlen")
    grid_1850 <- loadGridData(dataset = file_1850, var = "pcwd_maxlen")
    
    # Set spatial projection
    grid_1420 <- setGridProj(grid = grid_1420, proj = proj4string(refregions))
    grid_1850 <- setGridProj(grid = grid_1850, proj = proj4string(refregions))
    
    # Perform spatial overlay
    grid.eu_1420 <- overGrid(grid_1420, WCE)
    grid.eu_1850 <- overGrid(grid_1850, WCE)
    
    # Extract data arrays
    data_array_1420 <- grid.eu_1420$Data[1:430,,]
    data_array_1850 <- grid.eu_1850$Data
    
    # Combine data arrays along the time dimension
    combined_data_array <- abind::abind(data_array_1420, data_array_1850, along = 1)
    
    # Compute spatial average for each time step
    spatial_avg <- apply(combined_data_array, 1, function(slice) {
      mean(slice, na.rm = TRUE) # Compute mean for the spatial dimensions, ignoring NA
    })
    
    # Store the spatial average in the list
    spatial_avg_list[[em]] <- spatial_avg
  } else {
    warning(paste("Missing data for ensemble member:", em))
  }
}

# Combine all spatial averages into a single array with dimensions 160 x EMs
result_array.wce <- do.call(cbind, spatial_avg_list)

# Check the result
#dim(result_array.wce) # Should be 160 x EMs
```

```{r plot all EMs as spaghetti}
# Assuming your years range from 1420 to 2009
years <- 1420:2009

# Convert the matrix to a data frame
result_df <- as.data.frame(result_array.wce)

# Add a column for years
result_df$Year <- years


# Reshape to long format
result_long <- pivot_longer(
  result_df,
  cols = -Year,  # All columns except 'Year' are to be gathered
  names_to = "Ensemble_Member",
  values_to = "Duration"
)

# # Create the spaghetti plot
# ggplot(result_long, aes(x = Year, y = Duration, color = Ensemble_Member)) +
#   geom_line() +
#   labs(
#     title = "Drought Duration for WCE",
#     x = "Year",
#     y = "Max Drought Duration (days)",
#     color = "Ensemble Member"
#   ) +
#   theme_classic() +
#   ylim(0, 2000) +  # Set y-axis limits
#   theme(legend.position = "right")

# Specify the ensemble member you want to plot
ensemble_to_plot <- "m015_tidy"

# Filter the data for the chosen ensemble member
filtered_data <- result_long %>%
  filter(Ensemble_Member == ensemble_to_plot)

# Create the plot for the single ensemble member
ggplot(filtered_data, aes(x = Year, y = Duration)) +
  geom_line(color = "blue") +  # Set the line color
  labs(
    title = paste("Plot of", ensemble_to_plot, "Over Time"),
    x = "Year",
    y = "Max Drought Duration (days)"
  ) +
  theme_classic()

```


```{r}
######calculate EVA for region i.e. WCE here for development
#new dataframe that contains a len value for 2 year return period for each 30yr sliding window

# Define the window size (here 31 years) and return period
window_size <- 50
return_period <- 2

# Time information for the combined period
time_info <- seq(from = as.numeric(1420), to = as.numeric(2009))


# Initialize a vector to store the 2-year return levels (one value per time step)
num_time_steps <- nrow(result_array.wce)
return_level_vector <- rep(NA, num_time_steps)

# Loop over time steps (ensuring a 31-year moving window)
for (t in (window_size + 1):(num_time_steps - window_size)) {
  # Extract the data for the current 31-year window across all ensemble members
  window_data <- result_array.wce[(t - window_size):(t + window_size), ]
  window_data <- as.vector(window_data) # Flatten the matrix to a single vector
  
  # Remove NA values (if any) before fitting
  window_data <- window_data[!is.na(window_data)]
  
  # Fit the GEV distribution to the combined data
  gev_fit <- fevd(window_data, type = "Gumbel", verbose = FALSE)
  
  # Calculate the 2-year return level
  return_level <- return.level(gev_fit, return.period = return_period)
  
  # Store the result in the vector
  return_level_vector[t] <- return_level
}


# Create a data.frame combining time and return levels
result_df_RL <- data.frame(
  time = time_info,
  return_level = return_level_vector
)
```

```{r}
ggplot(data = result_df_RL) +
  geom_line(mapping= aes(x=time, y=return_level))+
  ylim(min(result_df_RL$return_level), max(result_df_RL$return_level)) +
  xlim(min(result_df_RL$time), max(result_df_RL$time)) +
  labs(
    x = "Year", 
    y = "Max Consecutive dry days",
    title = "2-year return level - 100yr sliding window"
  ) +
  theme_classic()
```


```{r read in EMS all regions, eval=FALSE, echo=FALSE}
###############################read in data##################################
#as before but loop over all regions also, saving everything in an array
path <- "/storage/research/giub_geco/data_2/scratch/phelpap/ModESim"
folders <- list.files(path, full.names = TRUE, pattern = "m[0-9]{3}_tidy")

# Identify the target files
target_files <- file.path(folders, "02_2_pcwd_result_1850/PCWD_maxlen.nc")
target_files <- target_files[file.exists(target_files)]

# Extract unique ensemble member identifiers from folder names
ensemble_members <- unique(basename(folders))

# # List of regions to loop over --- remove ocean basins
# regions <- c("GIC", "NWN", "NEN", "WNA", "CNA", "ENA", "NCA", "SCA", "CAR", "NWS",
#              "NSA", "NES", "SAM", "SWS", "SES", "SSA", "NEU", "WCE", "EEU", "MED",
#              "SAH", "WAF", "CAF", "NEAF", "SEAF", "WSAF", "ESAF", "MDG", "RAR", "WSB",
#              "ESB", "RFE", "WCA", "ECA", "TIB", "EAS", "ARP", "SAS", "SEA", "NAU",
#              "CAU", "EAU", "SAU", "NZ")
regions <- c("NZ")
# Initialize a list to store results for all regions
regional_results <- list()

# Loop over all regions
for (region in regions) {
  # Extract the spatial object corresponding to the current region
  region_object <- refregions[c(region)]
  
  # Check if the subset is valid
  if (is.null(region_object)) {
    warning(paste("Region not found:", region))
    next
  }
  
  # Initialize a list to store spatial averages for each file in the current region
  spatial_avg_list <- list()
  
  # Loop over all ensemble member folders
  # Loop over all ensemble member folders
  for (em in ensemble_members) {
    # Construct the folder path for the current ensemble member
    folder <- file.path(path, em)
   # Construct file paths for the two time periods
   file_1420 <- file.path(folder, "02_2_pcwd_result_1420/PCWD_maxlen.nc")
   file_1850 <- file.path(folder, "02_2_pcwd_result_1850/PCWD_maxlen.nc")
  
   # Check if both files exist
   if (file.exists(file_1420) && file.exists(file_1850)) {
    # Load grid data for each time period
    grid_1420 <- loadGridData(dataset = file_1420, var = "pcwd_maxlen")
    grid_1850 <- loadGridData(dataset = file_1850, var = "pcwd_maxlen")
      
      # Set spatial projection
      grid_1420 <- setGridProj(grid = grid_1420, proj = proj4string(refregions))
      grid_1850 <- setGridProj(grid = grid_1850, proj = proj4string(refregions))
      
      # Perform spatial overlay for the current region
      grid_region_1420 <- overGrid(grid_1420, region_object)
      grid_region_1850 <- overGrid(grid_1850, region_object)
      
      # Extract data arrays
      data_array_1420 <- grid_region_1420$Data[1:430,,]
      data_array_1850 <- grid_region_1850$Data
      
      # Combine data arrays along the time dimension
      combined_data_array <- abind::abind(data_array_1420, data_array_1850, along = 1)
      
      # Compute spatial average for each time step
      spatial_avg <- apply(combined_data_array, 1, function(slice) {
        mean(slice, na.rm = TRUE) # Compute mean for the spatial dimensions, ignoring NA
      })
      
      # Store the spatial average in the list
      spatial_avg_list[[em]] <- spatial_avg
    } else {
      warning(paste("Missing data for ensemble member:", em, "in region:", region))
    }
  }
  
  # Combine all spatial averages into a single array for the current region
  result_array_region <- do.call(cbind, spatial_avg_list)
  
  # Store the result for the current region
  regional_results[[region]] <- result_array_region
}

#save calculated list
saveRDS(regional_results, file="~/cwd_global/data/regionalResults_duration.RData")

#Load with
regional_results_test <- readRDS("~/cwd_global/data/regionalResults_duration.RData")

```

## Assessing the change in frequency of 2-year drought events (Moderate drought)

```{r calculate return periods all regions 2yr, eval=FALSE, echo=FALSE }
use_rp <- 2    # return period of two years
nyears <- 30   # bin width

# From https://geco-bern.github.io/cwd/articles/cwd_example.html: 
# calculate return period as a function of the CWD extreme. Using the two 
# coefficients of the fitted distribution as arguments
calc_return_period <- function(x, loc, scale){
  1 / (1 - exp(-exp(-(x-loc)/scale)))
}

extract_loc <- function(mod){
  loc <- mod$results$par[ "location" ]
  if (!is.null(loc)){
    return(loc)
  } else {
    return(NA)
  }
}

extract_scale <- function(mod){
  scale <- mod$results$par[ "scale" ]
  if (!is.null(scale)){
    return(scale)
  } else {
    return(NA)
  }
}


# Initialize a list to store results for all regions
all_regions_results <- list()

# Loop through each region in regional_results
for (region in names(regional_results)) { #swap european_regions for regional_results for all regions
  # Extract the result array for the current region
  result_array_region <- regional_results[[region]]

  # Calculate magnitude of event with RP = X in reference period
  # Calculate the baseline 2-year return level using the first 30 years
  baseline <- as.vector(result_array_region[(1:nyears),])
  fit_ref <- extRemes::fevd(baseline, type = "Gumbel", method = "MLE", units = "years")
  cwd_ref <- extRemes::return.level(fit_ref, return.period = use_rp)

  # initialise
  rp_window <- rep(NA, nrow(result_array_region) - nyears + 1)

  for (window_start in 1:(nrow(result_array_region) - nyears + 1)){

    # Extract data for the current window
    window_data <- result_array_region[window_start:(window_start + nyears - 1), ]
  
    # Flatten the matrix into a single vector
    window_data <- as.vector(window_data)
  
    # Fit Gumbel distribution to the window data
    fit_window <- fevd(window_data, type = "Gumbel")

	  # determine return period of cwd_ref based on new fit (How much more/less probably is an event that corresponded to an X-yearly event in the reference period?)
	  rp_window[window_start] <- calc_return_period(cwd_ref, extract_loc(fit_window), extract_scale(fit_window))

  }
  # Create a dataframe for the current region
  time_info <- seq(from = as.numeric(1420), to = as.numeric(2009))  # Replace with actual time if available
  region_df <- data.frame(
    time = time_info[15:575],
    RP = rp_window,
    region = region
  )
  
  # Store the region's dataframe in the results list
  all_regions_results[[region]] <- region_df
}
  
# Combine all region results into a single dataframe
combined_results <- do.call(rbind, all_regions_results)

# Save or process the combined dataframe
# Example: Save to a CSV file
write.csv(combined_results, "~/cwd_global/data/2yr_return_periods_regions_duration.csv", row.names = FALSE)


```

### Frequency changes of 2-yr return period events for all IPCC regions:

```{r timeseries and map plots for each region, echo=FALSE, warning=FALSE, message=FALSE}
###### 1. Read in return period data
# Load the CSV files for each window size
#df_10yr <- read.csv("~/cwd_global/data/effective_return_periods_regions_10.csv")
combined_df <- read.csv("~/cwd_global/data/2yr_return_periods_regions_duration.csv")
#df_100yr <- read.csv("~/cwd_global/data/effective_return_periods_regions_100.csv")

# Add a new column to identify window size for each dataframe
#df_10yr$window_size <- "10yr"
combined_df$window_size <- "30yr"
#df_100yr$window_size <- "100yr"

# Combine the three dataframes into one
#combined_df <- bind_rows(df_10yr, df_30yr, df_100yr)

####################################### EUROPE #####################################
##### Step 2: Filter European regions for the map and timeseries
# Filter regions for Europe
selected_continent <- "Europe"
sel_regions <- continent_mapping[[selected_continent]]

# Filter combined data for timeseries 
combined_df_sel <- combined_df %>% filter(region %in% sel_regions)

# Filter spatial data for map
sel_regions_sf <- refregions_sf %>% filter(continent %in% selected_continent)

# Define bounding box for Europe
bbox <- c(xmin = -30, xmax = 70, ymin = 25, ymax = 75)  # Approximate bounding box for Europe

# european_regions_sf <- refregions_sf %>% filter(continent == "Europe")
# # Define the bounding box for Europe
# europe_bbox <- c(xmin = -30, xmax = 70, ymin = 25, ymax = 75)  # Approximate bounding box for Europe


#### Step 4: Create the map
map_plot <- ggplot() +
  geom_sf(data = land, fill = "lightgray", color = NA) +  # Fill land areas
  geom_sf(data = sel_regions_sf, aes(fill = continent), color = "black", alpha = 0.6) +  # Transparent overlay
  geom_sf_text(data = region_labels, aes(label = label), size = 3, color = "black", check_overlap = TRUE) +  # Add region names
  scale_fill_manual(values = continent_colors, name = "") +
  theme_classic() +
  labs(title = "IPCC Regions", ylabs="", xlabs="") +
  theme(
    plot.title = element_text(size = 14, face = "bold"),
    plot.subtitle = element_text(size = 12),
    legend.position = "bottom"
  ) +
  coord_sf(xlim = bbox[1:2], ylim = bbox[3:4], expand = FALSE)  # Crop the map to Europe

##### Step 5: Plot the time series data with faceting
time_series_plot <- ggplot(combined_df_sel, aes(x = time, y = RP, color = window_size)) +
  geom_line() +  # Plot lines for each region's return period
  geom_hline(yintercept = 2, linetype = "dashed", color = "black") +  # Add a reference line for 2-year return period
  labs(
    x = "Year",
    y = "Effective Return Period",
    title = "Frequency Change of 2-Year Events"
  ) +
  scale_color_manual(name = "Window Size", values = c("10yr" = "cadetblue", "30yr" = "chocolate3", "100yr" = "chartreuse")) +
  theme_classic() +
  theme(
    legend.position = "top",
    plot.title = element_text(hjust = 0.5, face = "bold"),  # Center the title
    strip.text = element_text(size = 10),  # Size for facet labels
    strip.background = element_rect(fill = "pink")
  ) +
  facet_wrap(~region, scales = "free_y"
             )  # Facet by region with independent y-axis scales

##### Step 6: Arrange the two plots side by side using patchwork
# Explicitly control the layout with patchwork

# Arrange the Map and Time Series Side by Side
grid.arrange(
  map_plot, time_series_plot,
  ncol = 2,  # Side-by-side layout
  widths = c(1, 2)  # Adjust the relative width of the plots
)


######################################ASIA#######################################
##### Step 2: Filter Asian regions for the map and timeseries
# Filter regions for Asian
selected_continent <- "Asia"
sel_regions <- continent_mapping[[selected_continent]]

# Filter combined data for timeseries 
combined_df_sel <- combined_df %>% filter(region %in% sel_regions)

# Filter spatial data for map
sel_regions_sf <- refregions_sf %>% filter(continent %in% selected_continent)

# Define bounding box for Asia
bbox <- c(xmin = 30, xmax = 190, ymin = -20, ymax = 90)  # Approximate bounding box for Europe

# european_regions_sf <- refregions_sf %>% filter(continent == "Europe")
# # Define the bounding box for Europe
# europe_bbox <- c(xmin = -30, xmax = 70, ymin = 25, ymax = 75)  # Approximate bounding box for Europe


#### Step 4: Create the map
map_plot_A <- ggplot() +
  geom_sf(data = land, fill = "lightgray", color = NA) +  # Fill land areas
  geom_sf(data = sel_regions_sf, aes(fill = continent), color = "black", alpha = 0.6) +  # Transparent overlay
  geom_sf_text(data = region_labels, aes(label = label), size = 3, color = "black", check_overlap = TRUE) +  # Add region names
  scale_fill_manual(values = continent_colors, name = "") +
  theme_classic() +
  labs(title = "IPCC Regions", ylabs="", xlabs="") +
  theme(
    plot.title = element_text(size = 14, face = "bold"),
    plot.subtitle = element_text(size = 12),
    legend.position = "bottom"
  ) +
  coord_sf(xlim = bbox[1:2], ylim = bbox[3:4], expand = FALSE)  # Crop the map to Asia

##### Step 5: Plot the time series data with faceting
time_series_plot_A <- ggplot(combined_df_sel, aes(x = time, y = RP, color = window_size)) +
  geom_line() +  # Plot lines for each region's return period
  geom_hline(yintercept = 2, linetype = "dashed", color = "black") +  # Add a reference line for 2-year return period
  labs(
    x = "Year",
    y = "Effective Return Period",
    title = "Frequency Change of 2-Year Events"
  ) +
  scale_color_manual(name = "Window Size", values = c("10yr" = "cadetblue", "30yr" = "chocolate3", "100yr" = "chartreuse")) +
  theme_classic() +
  theme(
    legend.position = "top",
    plot.title = element_text(hjust = 0.5, face = "bold"),  # Center the title
    strip.text = element_text(size = 10),  # Size for facet labels
    strip.background = element_rect(fill = "orange")
  ) +
  facet_wrap(~region, scales = "free_y")  # Facet by region with independent y-axis scales

##### Step 6: Arrange the two plots side by side using patchwork
# Explicitly control the layout with patchwork

# Arrange the Map and Time Series Side by Side
grid.arrange(
  map_plot_A, time_series_plot_A,
  ncol = 2,  # Side-by-side layout
  widths = c(1, 2)  # Adjust the relative width of the plots
)


###################################### OCEANIA #######################################
##### Step 2: Filter Oceanian regions for the map and timeseries
# Filter regions for Oceania
selected_continent <- "Australia"
sel_regions <- continent_mapping[[selected_continent]]

# Filter combined data for timeseries 
combined_df_sel <- combined_df %>% filter(region %in% sel_regions)

# Filter spatial data for map
sel_regions_sf <- refregions_sf %>% filter(continent %in% selected_continent)

# Define bounding box for Oceania
bbox <- c(xmin = 100, xmax = 190, ymin = -60, ymax = 0)  # Approximate bounding box for Oceania

#### Step 4: Create the map
map_plot_B <- ggplot() +
  geom_sf(data = land, fill = "lightgray", color = NA) +  # Fill land areas
  geom_sf(data = sel_regions_sf, aes(fill = continent), color = "black", alpha = 0.6) +  # Transparent overlay
  geom_sf_text(data = region_labels, aes(label = label), size = 3, color = "black", check_overlap = TRUE) +  # Add region names
  scale_fill_manual(values = continent_colors, name = "") +
  theme_classic() +
  labs(title = "IPCC Regions", ylabs="", xlabs="") +
  theme(
    plot.title = element_text(size = 14, face = "bold"),
    plot.subtitle = element_text(size = 12),
    legend.position = "bottom"
  ) +
  coord_sf(xlim = bbox[1:2], ylim = bbox[3:4], expand = FALSE)  # Crop the map to Asia

##### Step 5: Plot the time series data with faceting
time_series_plot_B <- ggplot(combined_df_sel, aes(x = time, y = RP, color = window_size)) +
  geom_line() +  # Plot lines for each region's return period
  geom_hline(yintercept = 2, linetype = "dashed", color = "black") +  # Add a reference line for 2-year return period
  labs(
    x = "Year",
    y = "Effective Return Period",
    title = "Frequency Change of 2-Year Events"
  ) +
  scale_color_manual(name = "Window Size", values = c("10yr" = "cadetblue", "30yr" = "chocolate3", "100yr" = "chartreuse")) +
  theme_classic() +
  theme(
    legend.position = "top",
    plot.title = element_text(hjust = 0.5, face = "bold"),  # Center the title
    strip.text = element_text(size = 10),  # Size for facet labels
    strip.background = element_rect(fill = "blue")
  ) +
  facet_wrap(~region, scales = "free_y")  # Facet by region with independent y-axis scales

##### Step 6: Arrange the two plots side by side using patchwork
# Explicitly control the layout with patchwork

# Arrange the Map and Time Series Side by Side
grid.arrange(
  map_plot_B, time_series_plot_B,
  ncol = 2,  # Side-by-side layout
  widths = c(1, 2)  # Adjust the relative width of the plots
)


###################################### AFRICA #######################################
##### Step 2: Filter African regions for the map and timeseries
# Filter regions for Africa
selected_continent <- "Africa"
sel_regions <- continent_mapping[[selected_continent]]

# Filter combined data for timeseries 
combined_df_sel <- combined_df %>% filter(region %in% sel_regions)

# Filter spatial data for map
sel_regions_sf <- refregions_sf %>% filter(continent %in% selected_continent)

# Define bounding box for Africa
bbox <- c(xmin = -30, xmax = 60, ymin = -40, ymax = 40)  # Approximate bounding box for Oceania

#### Step 4: Create the map
map_plot_C <- ggplot() +
  geom_sf(data = land, fill = "lightgray", color = NA) +  # Fill land areas
  geom_sf(data = sel_regions_sf, aes(fill = continent), color = "black", alpha = 0.6) +  # Transparent overlay
  geom_sf_text(data = region_labels, aes(label = label), size = 3, color = "black", check_overlap = TRUE) +  # Add region names
  scale_fill_manual(values = continent_colors, name = "") +
  theme_classic() +
  labs(title = "IPCC Regions", ylabs="", xlabs="") +
  theme(
    plot.title = element_text(size = 14, face = "bold"),
    plot.subtitle = element_text(size = 12),
    legend.position = "bottom"
  ) +
  coord_sf(xlim = bbox[1:2], ylim = bbox[3:4], expand = FALSE)  # Crop the map to Asia

##### Step 5: Plot the time series data with faceting
time_series_plot_C <- ggplot(combined_df_sel, aes(x = time, y = RP, color = window_size)) +
  geom_line() +  # Plot lines for each region's return period
  geom_hline(yintercept = 2, linetype = "dashed", color = "black") +  # Add a reference line for 2-year return period
  labs(
    x = "Year",
    y = "Effective Return Period",
    title = "Frequency Change of 2-Year Events"
  ) +
  scale_color_manual(name = "Window Size", values = c("10yr" = "cadetblue", "30yr" = "chocolate3", "100yr" = "chartreuse")) +
  theme_classic() +
  theme(
    legend.position = "top",
    plot.title = element_text(hjust = 0.5, face = "bold"),  # Center the title
    strip.text = element_text(size = 10),  # Size for facet labels
    strip.background = element_rect(fill = "purple")
  ) +
  facet_wrap(~region, scales = "free_y")  # Facet by region with independent y-axis scales

##### Step 6: Arrange the two plots side by side using patchwork
# Explicitly control the layout with patchwork

# Arrange the Map and Time Series Side by Side
grid.arrange(
  map_plot_C, time_series_plot_C,
  ncol = 2,  # Side-by-side layout
  widths = c(1, 2)  # Adjust the relative width of the plots
)


###################################### N AMERICA #######################################
##### Step 2: Filter N AMERICA regions for the map and timeseries
# Filter regions for N America
selected_continent <- "North America"
sel_regions <- continent_mapping[[selected_continent]]

# Filter combined data for timeseries 
combined_df_sel <- combined_df %>% filter(region %in% sel_regions)

# Filter spatial data for map
sel_regions_sf <- refregions_sf %>% filter(continent %in% selected_continent)

# Define bounding box for N America
bbox <- c(xmin = -180, xmax = -10, ymin = 20, ymax = 90)  # Approximate bounding box for Oceania

#### Step 4: Create the map
map_plot_D <- ggplot() +
  geom_sf(data = land, fill = "lightgray", color = NA) +  # Fill land areas
  geom_sf(data = sel_regions_sf, aes(fill = continent), color = "black", alpha = 0.6) +  # Transparent overlay
  geom_sf_text(data = region_labels, aes(label = label), size = 3, color = "black", check_overlap = TRUE) +  # Add region names
  scale_fill_manual(values = continent_colors, name = "") +
  theme_classic() +
  labs(title = "IPCC Regions", ylabs="", xlabs="") +
  theme(
    plot.title = element_text(size = 14, face = "bold"),
    plot.subtitle = element_text(size = 12),
    legend.position = "bottom"
  ) +
  coord_sf(xlim = bbox[1:2], ylim = bbox[3:4], expand = FALSE)  # Crop the map to Asia

##### Step 5: Plot the time series data with faceting
time_series_plot_D <- ggplot(combined_df_sel, aes(x = time, y = RP, color = window_size)) +
  geom_line() +  # Plot lines for each region's return period
  geom_hline(yintercept = 2, linetype = "dashed", color = "black") +  # Add a reference line for 2-year return period
  labs(
    x = "Year",
    y = "Effective Return Period",
    title = "Frequency Change of 2-Year Events"
  ) +
  scale_color_manual(name = "Window Size", values = c("10yr" = "cadetblue", "30yr" = "chocolate3", "100yr" = "chartreuse")) +
  theme_classic() +
  theme(
    legend.position = "top",
    plot.title = element_text(hjust = 0.5, face = "bold"),  # Center the title
    strip.text = element_text(size = 10),  # Size for facet labels
    strip.background = element_rect(fill = "lightgreen")
  ) +
  facet_wrap(~region, scales = "free_y")  # Facet by region with independent y-axis scales

##### Step 6: Arrange the two plots side by side using patchwork
# Explicitly control the layout with patchwork

# Arrange the Map and Time Series Side by Side
grid.arrange(
  map_plot_D, time_series_plot_D,
  ncol = 2,  # Side-by-side layout
  widths = c(1, 2)  # Adjust the relative width of the plots
)


###################################### C AMERICA #######################################
##### Step 2: Filter C AMERICA regions for the map and timeseries
# Filter regions for C America
selected_continent <- "Central America"
sel_regions <- continent_mapping[[selected_continent]]

# Filter combined data for timeseries 
combined_df_sel <- combined_df %>% filter(region %in% sel_regions)

# Filter spatial data for map
sel_regions_sf <- refregions_sf %>% filter(continent %in% selected_continent)

# Define bounding box for C America
bbox <- c(xmin = -130, xmax = -50, ymin = 0, ymax = 40)  # Approximate bounding box for Oceania

#### Step 4: Create the map
map_plot_E <- ggplot() +
  geom_sf(data = land, fill = "lightgray", color = NA) +  # Fill land areas
  geom_sf(data = sel_regions_sf, aes(fill = continent), color = "black", alpha = 0.6) +  # Transparent overlay
  geom_sf_text(data = region_labels, aes(label = label), size = 3, color = "black", check_overlap = TRUE) +  # Add region names
  scale_fill_manual(values = continent_colors, name = "") +
  theme_classic() +
  labs(title = "IPCC Regions", ylabs="", xlabs="") +
  theme(
    plot.title = element_text(size = 14, face = "bold"),
    plot.subtitle = element_text(size = 12),
    legend.position = "bottom"
  ) +
  coord_sf(xlim = bbox[1:2], ylim = bbox[3:4], expand = FALSE)  # Crop the map to Asia

##### Step 5: Plot the time series data with faceting
time_series_plot_E <- ggplot(combined_df_sel, aes(x = time, y = RP, color = window_size)) +
  geom_line() +  # Plot lines for each region's return period
  geom_hline(yintercept = 2, linetype = "dashed", color = "black") +  # Add a reference line for 2-year return period
  labs(
    x = "Year",
    y = "Effective Return Period",
    title = "Frequency Change of 2-Year Events"
  ) +
  scale_color_manual(name = "Window Size", values = c("10yr" = "cadetblue", "30yr" = "chocolate3", "100yr" = "chartreuse")) +
  theme_classic() +
  theme(
    legend.position = "top",
    plot.title = element_text(hjust = 0.5, face = "bold"),  # Center the title
    strip.text = element_text(size = 10),  # Size for facet labels
    strip.background = element_rect(fill = "lightblue")
  ) +
  facet_wrap(~region, scales = "free_y")  # Facet by region with independent y-axis scales

##### Step 6: Arrange the two plots side by side using patchwork
# Explicitly control the layout with patchwork

# Arrange the Map and Time Series Side by Side
grid.arrange(
  map_plot_E, time_series_plot_E,
  ncol = 2,  # Side-by-side layout
  widths = c(1, 2)  # Adjust the relative width of the plots
)


###################################### S AMERICA #######################################
##### Step 2: Filter S AMERICA regions for the map and timeseries
# Filter regions for S America
selected_continent <- "South America"
sel_regions <- continent_mapping[[selected_continent]]

# Filter combined data for timeseries 
combined_df_sel <- combined_df %>% filter(region %in% sel_regions)

# Filter spatial data for map
sel_regions_sf <- refregions_sf %>% filter(continent %in% selected_continent)

# Define bounding box for S America
bbox <- c(xmin = -90, xmax = -30, ymin = -60, ymax = 15)  # Approximate bounding box for Oceania

#### Step 4: Create the map
map_plot_F <- ggplot() +
  geom_sf(data = land, fill = "lightgray", color = NA) +  # Fill land areas
  geom_sf(data = sel_regions_sf, aes(fill = continent), color = "black", alpha = 0.6) +  # Transparent overlay
  geom_sf_text(data = region_labels, aes(label = label), size = 3, color = "black", check_overlap = TRUE) +  # Add region names
  scale_fill_manual(values = continent_colors, name = "") +
  theme_classic() +
  labs(title = "IPCC Regions", ylabs="", xlabs="") +
  theme(
    plot.title = element_text(size = 14, face = "bold"),
    plot.subtitle = element_text(size = 12),
    legend.position = "bottom"
  ) +
  coord_sf(xlim = bbox[1:2], ylim = bbox[3:4], expand = FALSE)  # Crop the map to South America

##### Step 5: Plot the time series data with faceting
time_series_plot_F <- ggplot(combined_df_sel, aes(x = time, y = RP, color = window_size)) +
  geom_line() +  # Plot lines for each region's return period
  geom_hline(yintercept = 2, linetype = "dashed", color = "black") +  # Add a reference line for 2-year return period
  labs(
    x = "Year",
    y = "Effective Return Period",
    title = "Frequency Change of 2-Year Events"
  ) +
  scale_color_manual(name = "Window Size", values = c("10yr" = "cadetblue", "30yr" = "chocolate3", "100yr" = "chartreuse")) +
  theme_classic() +
  theme(
    legend.position = "top",
    plot.title = element_text(hjust = 0.5, face = "bold"),  # Center the title
    strip.text = element_text(size = 10),  # Size for facet labels
    strip.background = element_rect(fill = "yellow")
  ) +
  facet_wrap(~region, scales = "free_y")  # Facet by region with independent y-axis scales

##### Step 6: Arrange the two plots side by side using patchwork
# Explicitly control the layout with patchwork

# Arrange the Map and Time Series Side by Side
grid.arrange(
  map_plot_F, time_series_plot_F,
  ncol = 2,  # Side-by-side layout
  widths = c(1, 2)  # Adjust the relative width of the plots
)
```

## Assessing the change in frequency of 20-year drought events (Severe drought)

```{r calculate return periods all regions 20 yr, echo=FALSE, message=FALSE, eval=FALSE}
use_rp <- 20    # return period of two years
nyears <- 30   # bin width

# From https://geco-bern.github.io/cwd/articles/cwd_example.html: 
# calculate return period as a function of the CWD extreme. Using the two 
# coefficients of the fitted distribution as arguments
calc_return_period <- function(x, loc, scale){
  1 / (1 - exp(-exp(-(x-loc)/scale)))
}

extract_loc <- function(mod){
  loc <- mod$results$par[ "location" ]
  if (!is.null(loc)){
    return(loc)
  } else {
    return(NA)
  }
}

extract_scale <- function(mod){
  scale <- mod$results$par[ "scale" ]
  if (!is.null(scale)){
    return(scale)
  } else {
    return(NA)
  }
}


# Initialize a list to store results for all regions
all_regions_results <- list()

# Loop through each region in regional_results
for (region in names(regional_results)) { #swap european_regions for regional_results for all regions
  # Extract the result array for the current region
  result_array_region <- regional_results[[region]]

  # Calculate magnitude of event with RP = X in reference period
  # Calculate the baseline 2-year return level using the first 30 years
  baseline <- as.vector(result_array_region[(1:nyears),])
  fit_ref <- extRemes::fevd(baseline, type = "Gumbel", method = "MLE", units = "years")
  cwd_ref <- extRemes::return.level(fit_ref, return.period = use_rp)

  # initialise
  rp_window <- rep(NA, nrow(result_array_region) - nyears + 1)

  for (window_start in 1:(nrow(result_array_region) - nyears + 1)){

    # Extract data for the current window
    window_data <- result_array_region[window_start:(window_start + nyears - 1), ]
  
    # Flatten the matrix into a single vector
    window_data <- as.vector(window_data)
  
    # Fit Gumbel distribution to the window data
    fit_window <- fevd(window_data, type = "Gumbel")

	  # determine return period of cwd_ref based on new fit (How much more/less probably is an event that corresponded to an X-yearly event in the reference period?)
	  rp_window[window_start] <- calc_return_period(cwd_ref, extract_loc(fit_window), extract_scale(fit_window))

  }
  # Create a dataframe for the current region
  time_info <- seq(from = as.numeric(1420), to = as.numeric(2009))  # Replace with actual time if available
  region_df <- data.frame(
    time = time_info[15:575],
    RP = rp_window,
    region = region
  )
  
  # Store the region's dataframe in the results list
  all_regions_results[[region]] <- region_df
}
  
# Combine all region results into a single dataframe
combined_results <- do.call(rbind, all_regions_results)

# Save or process the combined dataframe
# Example: Save to a CSV file
write.csv(combined_results, "~/cwd_global/data/20yr_return_periods_regions_duration.csv", row.names = FALSE)
```

```{r timeseries and map plots for each region 20 yr, echo=FALSE, warning=FALSE, message=FALSE}
###### 1. Read in return period data
# Load the CSV files for each window size
combined_df <- read.csv("~/cwd_global/data/20yr_return_periods_regions_duration.csv")
#df_70yr <- read.csv("~/cwd_global/data/20yr_effective_return_periods_regions_70.csv")  #called RP effective_return_period here
#df_100yr <- read.csv("~/cwd_global/data/20yr_effective_return_periods_regions_100.csv")

# Add a new column to identify window size for each dataframe
combined_df$window_size <- "30yr"
#df_70yr$window_size <- "70yr"
#df_100yr$window_size <- "100yr"

# Combine the three dataframes into one
#combined_df <- bind_rows(df_40yr, df_70yr, df_100yr)

####################################### EUROPE #####################################
##### Step 2: Filter European regions for the map and timeseries
# Filter regions for Europe
selected_continent <- "Europe"
sel_regions <- continent_mapping[[selected_continent]]

# Filter combined data for timeseries 
combined_df_sel <- combined_df %>% filter(region %in% sel_regions)

# Filter spatial data for map
sel_regions_sf <- refregions_sf %>% filter(continent %in% selected_continent)

# Define bounding box for Europe
bbox <- c(xmin = -30, xmax = 70, ymin = 25, ymax = 75)  # Approximate bounding box for Europe

# european_regions_sf <- refregions_sf %>% filter(continent == "Europe")
# # Define the bounding box for Europe
# europe_bbox <- c(xmin = -30, xmax = 70, ymin = 25, ymax = 75)  # Approximate bounding box for Europe


#### Step 4: Create the map
map_plot <- ggplot() +
  geom_sf(data = land, fill = "lightgray", color = NA) +  # Fill land areas
  geom_sf(data = sel_regions_sf, aes(fill = continent), color = "black", alpha = 0.6) +  # Transparent overlay
  geom_sf_text(data = region_labels, aes(label = label), size = 3, color = "black", check_overlap = TRUE) +  # Add region names
  scale_fill_manual(values = continent_colors, name = "") +
  theme_classic() +
  labs(title = "IPCC Regions", ylabs="", xlabs="") +
  theme(
    plot.title = element_text(size = 14, face = "bold"),
    plot.subtitle = element_text(size = 12),
    legend.position = "bottom"
  ) +
  coord_sf(xlim = bbox[1:2], ylim = bbox[3:4], expand = FALSE)  # Crop the map to Europe

##### Step 5: Plot the time series data with faceting
time_series_plot <- ggplot(combined_df_sel, aes(x = time, y = RP, color = window_size)) +
  geom_line() +  # Plot lines for each region's return period
  geom_hline(yintercept = 20, linetype = "dashed", color = "black") +  # Add a reference line for 2-year return period
  labs(
    x = "Year",
    y = "Effective Return Period",
    title = "Frequency Change of 20-Year Events"
  ) +
  scale_color_manual(name = "Window Size", values = c("30yr" = "cadetblue4", "70yr" = "chocolate1", "100yr" = "chartreuse")) +
  theme_classic() +
  theme(
    legend.position = "top",
    plot.title = element_text(hjust = 0.5, face = "bold"),  # Center the title
    strip.text = element_text(size = 10),  # Size for facet labels
    strip.background = element_rect(fill = "pink")
  ) +
  facet_wrap(~region, scales = "free_y"
             )  # Facet by region with independent y-axis scales

##### Step 6: Arrange the two plots side by side using patchwork
# Explicitly control the layout with patchwork

# Arrange the Map and Time Series Side by Side
grid.arrange(
  map_plot, time_series_plot,
  ncol = 2,  # Side-by-side layout
  widths = c(1, 2)  # Adjust the relative width of the plots
)


######################################ASIA#######################################
##### Step 2: Filter Asian regions for the map and timeseries
# Filter regions for Asian
selected_continent <- "Asia"
sel_regions <- continent_mapping[[selected_continent]]

# Filter combined data for timeseries 
combined_df_sel <- combined_df %>% filter(region %in% sel_regions)

# Filter spatial data for map
sel_regions_sf <- refregions_sf %>% filter(continent %in% selected_continent)

# Define bounding box for Asia
bbox <- c(xmin = 30, xmax = 190, ymin = -20, ymax = 90)  # Approximate bounding box for Europe

# european_regions_sf <- refregions_sf %>% filter(continent == "Europe")
# # Define the bounding box for Europe
# europe_bbox <- c(xmin = -30, xmax = 70, ymin = 25, ymax = 75)  # Approximate bounding box for Europe


#### Step 4: Create the map
map_plot_A <- ggplot() +
  geom_sf(data = land, fill = "lightgray", color = NA) +  # Fill land areas
  geom_sf(data = sel_regions_sf, aes(fill = continent), color = "black", alpha = 0.6) +  # Transparent overlay
  geom_sf_text(data = region_labels, aes(label = label), size = 3, color = "black", check_overlap = TRUE) +  # Add region names
  scale_fill_manual(values = continent_colors, name = "") +
  theme_classic() +
  labs(title = "IPCC Regions", ylabs="", xlabs="") +
  theme(
    plot.title = element_text(size = 14, face = "bold"),
    plot.subtitle = element_text(size = 12),
    legend.position = "bottom"
  ) +
  coord_sf(xlim = bbox[1:2], ylim = bbox[3:4], expand = FALSE)  # Crop the map to Asia

##### Step 5: Plot the time series data with faceting
time_series_plot_A <- ggplot(combined_df_sel, aes(x = time, y = RP, color = window_size)) +
  geom_line() +  # Plot lines for each region's return period
  geom_hline(yintercept = 20, linetype = "dashed", color = "black") +  # Add a reference line for 2-year return period
  labs(
    x = "Year",
    y = "Effective Return Period",
    title = "Frequency Change of 20-Year Events"
  ) +
  scale_color_manual(name = "Window Size", values = c("30yr" = "cadetblue4", "70yr" = "chocolate1", "100yr" = "chartreuse")) +
  theme_classic() +
  theme(
    legend.position = "top",
    plot.title = element_text(hjust = 0.5, face = "bold"),  # Center the title
    strip.text = element_text(size = 10),  # Size for facet labels
    strip.background = element_rect(fill = "orange")
  ) +
  facet_wrap(~region, scales = "free_y")  # Facet by region with independent y-axis scales

##### Step 6: Arrange the two plots side by side using patchwork
# Explicitly control the layout with patchwork

# Arrange the Map and Time Series Side by Side
grid.arrange(
  map_plot_A, time_series_plot_A,
  ncol = 2,  # Side-by-side layout
  widths = c(1, 2)  # Adjust the relative width of the plots
)


###################################### OCEANIA #######################################
##### Step 2: Filter Oceanian regions for the map and timeseries
# Filter regions for Oceania
selected_continent <- "Australia"
sel_regions <- continent_mapping[[selected_continent]]

# Filter combined data for timeseries 
combined_df_sel <- combined_df %>% filter(region %in% sel_regions)

# Filter spatial data for map
sel_regions_sf <- refregions_sf %>% filter(continent %in% selected_continent)

# Define bounding box for Oceania
bbox <- c(xmin = 100, xmax = 190, ymin = -60, ymax = 0)  # Approximate bounding box for Oceania

#### Step 4: Create the map
map_plot_B <- ggplot() +
  geom_sf(data = land, fill = "lightgray", color = NA) +  # Fill land areas
  geom_sf(data = sel_regions_sf, aes(fill = continent), color = "black", alpha = 0.6) +  # Transparent overlay
  geom_sf_text(data = region_labels, aes(label = label), size = 3, color = "black", check_overlap = TRUE) +  # Add region names
  scale_fill_manual(values = continent_colors, name = "") +
  theme_classic() +
  labs(title = "IPCC Regions", ylabs="", xlabs="") +
  theme(
    plot.title = element_text(size = 14, face = "bold"),
    plot.subtitle = element_text(size = 12),
    legend.position = "bottom"
  ) +
  coord_sf(xlim = bbox[1:2], ylim = bbox[3:4], expand = FALSE)  # Crop the map to Asia

##### Step 5: Plot the time series data with faceting
time_series_plot_B <- ggplot(combined_df_sel, aes(x = time, y = RP, color = window_size)) +
  geom_line() +  # Plot lines for each region's return period
  geom_hline(yintercept = 20, linetype = "dashed", color = "black") +  # Add a reference line for 2-year return period
  labs(
    x = "Year",
    y = "Effective Return Period",
    title = "Frequency Change of 20-Year Events"
  ) +
  scale_color_manual(name = "Window Size", values = c("30yr" = "cadetblue4", "70yr" = "chocolate1", "100yr" = "chartreuse")) +
  theme_classic() +
  theme(
    legend.position = "top",
    plot.title = element_text(hjust = 0.5, face = "bold"),  # Center the title
    strip.text = element_text(size = 10),  # Size for facet labels
    strip.background = element_rect(fill = "blue")
  ) +
  facet_wrap(~region, scales = "free_y")  # Facet by region with independent y-axis scales

##### Step 6: Arrange the two plots side by side using patchwork
# Explicitly control the layout with patchwork

# Arrange the Map and Time Series Side by Side
grid.arrange(
  map_plot_B, time_series_plot_B,
  ncol = 2,  # Side-by-side layout
  widths = c(1, 2)  # Adjust the relative width of the plots
)


###################################### AFRICA #######################################
##### Step 2: Filter African regions for the map and timeseries
# Filter regions for Africa
selected_continent <- "Africa"
sel_regions <- continent_mapping[[selected_continent]]

# Filter combined data for timeseries 
combined_df_sel <- combined_df %>% filter(region %in% sel_regions)

# Filter spatial data for map
sel_regions_sf <- refregions_sf %>% filter(continent %in% selected_continent)

# Define bounding box for Africa
bbox <- c(xmin = -30, xmax = 60, ymin = -30, ymax = 30)  # Approximate bounding box for Oceania

#### Step 4: Create the map
map_plot_C <- ggplot() +
  geom_sf(data = land, fill = "lightgray", color = NA) +  # Fill land areas
  geom_sf(data = sel_regions_sf, aes(fill = continent), color = "black", alpha = 0.6) +  # Transparent overlay
  geom_sf_text(data = region_labels, aes(label = label), size = 3, color = "black", check_overlap = TRUE) +  # Add region names
  scale_fill_manual(values = continent_colors, name = "") +
  theme_classic() +
  labs(title = "IPCC Regions", ylabs="", xlabs="") +
  theme(
    plot.title = element_text(size = 14, face = "bold"),
    plot.subtitle = element_text(size = 12),
    legend.position = "bottom"
  ) +
  coord_sf(xlim = bbox[1:2], ylim = bbox[3:4], expand = FALSE)  # Crop the map to Asia

##### Step 5: Plot the time series data with faceting
time_series_plot_C <- ggplot(combined_df_sel, aes(x = time, y = RP, color = window_size)) +
  geom_line() +  # Plot lines for each region's return period
  geom_hline(yintercept = 20, linetype = "dashed", color = "black") +  # Add a reference line for 2-year return period
  labs(
    x = "Year",
    y = "Effective Return Period",
    title = "Frequency Change of 20-Year Events"
  ) +
  scale_color_manual(name = "Window Size", values = c("30yr" = "cadetblue4", "70yr" = "chocolate1", "100yr" = "chartreuse")) +
  theme_classic() +
  theme(
    legend.position = "top",
    plot.title = element_text(hjust = 0.5, face = "bold"),  # Center the title
    strip.text = element_text(size = 10),  # Size for facet labels
    strip.background = element_rect(fill = "purple")
  ) +
  facet_wrap(~region, scales = "free_y")  # Facet by region with independent y-axis scales

##### Step 6: Arrange the two plots side by side using patchwork
# Explicitly control the layout with patchwork

# Arrange the Map and Time Series Side by Side
grid.arrange(
  map_plot_C, time_series_plot_C,
  ncol = 2,  # Side-by-side layout
  widths = c(1, 2)  # Adjust the relative width of the plots
)


###################################### N AMERICA #######################################
##### Step 2: Filter N AMERICA regions for the map and timeseries
# Filter regions for N America
selected_continent <- "North America"
sel_regions <- continent_mapping[[selected_continent]]

# Filter combined data for timeseries 
combined_df_sel <- combined_df %>% filter(region %in% sel_regions)

# Filter spatial data for map
sel_regions_sf <- refregions_sf %>% filter(continent %in% selected_continent)

# Define bounding box for N America
bbox <- c(xmin = -180, xmax = -10, ymin = 20, ymax = 90)  # Approximate bounding box for Oceania

#### Step 4: Create the map
map_plot_D <- ggplot() +
  geom_sf(data = land, fill = "lightgray", color = NA) +  # Fill land areas
  geom_sf(data = sel_regions_sf, aes(fill = continent), color = "black", alpha = 0.6) +  # Transparent overlay
  geom_sf_text(data = region_labels, aes(label = label), size = 3, color = "black", check_overlap = TRUE) +  # Add region names
  scale_fill_manual(values = continent_colors, name = "") +
  theme_classic() +
  labs(title = "IPCC Regions", ylabs="", xlabs="") +
  theme(
    plot.title = element_text(size = 14, face = "bold"),
    plot.subtitle = element_text(size = 12),
    legend.position = "bottom"
  ) +
  coord_sf(xlim = bbox[1:2], ylim = bbox[3:4], expand = FALSE)  # Crop the map to Asia

##### Step 5: Plot the time series data with faceting
time_series_plot_D <- ggplot(combined_df_sel, aes(x = time, y = RP, color = window_size)) +
  geom_line() +  # Plot lines for each region's return period
  geom_hline(yintercept = 20, linetype = "dashed", color = "black") +  # Add a reference line for 2-year return period
  labs(
    x = "Year",
    y = "Effective Return Period",
    title = "Frequency Change of 20-Year Events"
  ) +
  scale_color_manual(name = "Window Size", values = c("30yr" = "cadetblue4", "70yr" = "chocolate1", "100yr" = "chartreuse")) +
  theme_classic() +
  theme(
    legend.position = "top",
    plot.title = element_text(hjust = 0.5, face = "bold"),  # Center the title
    strip.text = element_text(size = 10),  # Size for facet labels
    strip.background = element_rect(fill = "lightgreen")
  ) +
  facet_wrap(~region, scales = "free_y")  # Facet by region with independent y-axis scales

##### Step 6: Arrange the two plots side by side using patchwork
# Explicitly control the layout with patchwork

# Arrange the Map and Time Series Side by Side
grid.arrange(
  map_plot_D, time_series_plot_D,
  ncol = 2,  # Side-by-side layout
  widths = c(1, 2)  # Adjust the relative width of the plots
)


###################################### C AMERICA #######################################
##### Step 2: Filter C AMERICA regions for the map and timeseries
# Filter regions for C America
selected_continent <- "Central America"
sel_regions <- continent_mapping[[selected_continent]]

# Filter combined data for timeseries 
combined_df_sel <- combined_df %>% filter(region %in% sel_regions)

# Filter spatial data for map
sel_regions_sf <- refregions_sf %>% filter(continent %in% selected_continent)

# Define bounding box for C America
bbox <- c(xmin = -130, xmax = -50, ymin = 0, ymax = 30)  # Approximate bounding box for Oceania

#### Step 4: Create the map
map_plot_E <- ggplot() +
  geom_sf(data = land, fill = "lightgray", color = NA) +  # Fill land areas
  geom_sf(data = sel_regions_sf, aes(fill = continent), color = "black", alpha = 0.6) +  # Transparent overlay
  geom_sf_text(data = region_labels, aes(label = label), size = 3, color = "black", check_overlap = TRUE) +  # Add region names
  scale_fill_manual(values = continent_colors, name = "") +
  theme_classic() +
  labs(title = "IPCC Regions", ylabs="", xlabs="") +
  theme(
    plot.title = element_text(size = 14, face = "bold"),
    plot.subtitle = element_text(size = 12),
    legend.position = "bottom"
  ) +
  coord_sf(xlim = bbox[1:2], ylim = bbox[3:4], expand = FALSE)  # Crop the map to Asia

##### Step 5: Plot the time series data with faceting
time_series_plot_E <- ggplot(combined_df_sel, aes(x = time, y = RP, color = window_size)) +
  geom_line() +  # Plot lines for each region's return period
  geom_hline(yintercept = 20, linetype = "dashed", color = "black") +  # Add a reference line for 2-year return period
  labs(
    x = "Year",
    y = "Effective Return Period",
    title = "Frequency Change of 20-Year Events"
  ) +
  scale_color_manual(name = "Window Size", values = c("30yr" = "cadetblue4", "70yr" = "chocolate1", "100yr" = "chartreuse")) +
  theme_classic() +
  theme(
    legend.position = "top",
    plot.title = element_text(hjust = 0.5, face = "bold"),  # Center the title
    strip.text = element_text(size = 10),  # Size for facet labels
    strip.background = element_rect(fill = "lightblue")
  ) +
  facet_wrap(~region, scales = "free_y")  # Facet by region with independent y-axis scales

##### Step 6: Arrange the two plots side by side using patchwork
# Explicitly control the layout with patchwork

# Arrange the Map and Time Series Side by Side
grid.arrange(
  map_plot_E, time_series_plot_E,
  ncol = 2,  # Side-by-side layout
  widths = c(1, 2)  # Adjust the relative width of the plots
)


###################################### S AMERICA #######################################
##### Step 2: Filter S AMERICA regions for the map and timeseries
# Filter regions for S America
selected_continent <- "South America"
sel_regions <- continent_mapping[[selected_continent]]

# Filter combined data for timeseries 
combined_df_sel <- combined_df %>% filter(region %in% sel_regions)

# Filter spatial data for map
sel_regions_sf <- refregions_sf %>% filter(continent %in% selected_continent)

# Define bounding box for S America
bbox <- c(xmin = -90, xmax = -30, ymin = -60, ymax = 15)  # Approximate bounding box for Oceania

#### Step 4: Create the map
map_plot_F <- ggplot() +
  geom_sf(data = land, fill = "lightgray", color = NA) +  # Fill land areas
  geom_sf(data = sel_regions_sf, aes(fill = continent), color = "black", alpha = 0.6) +  # Transparent overlay
  geom_sf_text(data = region_labels, aes(label = label), size = 3, color = "black", check_overlap = TRUE) +  # Add region names
  scale_fill_manual(values = continent_colors, name = "") +
  theme_classic() +
  labs(title = "IPCC Regions", ylabs="", xlabs="") +
  theme(
    plot.title = element_text(size = 14, face = "bold"),
    plot.subtitle = element_text(size = 12),
    legend.position = "bottom"
  ) +
  coord_sf(xlim = bbox[1:2], ylim = bbox[3:4], expand = FALSE)  # Crop the map to South America

##### Step 5: Plot the time series data with faceting
time_series_plot_F <- ggplot(combined_df_sel, aes(x = time, y = RP, color = window_size)) +
  geom_line() +  # Plot lines for each region's return period
  geom_hline(yintercept = 20, linetype = "dashed", color = "black") +  # Add a reference line for 20-year return period
  labs(
    x = "Year",
    y = "Effective Return Period",
    title = "Frequency Change of 20-Year Events"
  ) +
  scale_color_manual(name = "Window Size", values = c("30yr" = "cadetblue4", "70yr" = "chocolate1", "100yr" = "chartreuse")) +
  theme_classic() +
  theme(
    legend.position = "top",
    plot.title = element_text(hjust = 0.5, face = "bold"),  # Center the title
    strip.text = element_text(size = 10),  # Size for facet labels
    strip.background = element_rect(fill = "yellow")
  ) +
  facet_wrap(~region, scales = "free_y")  # Facet by region with independent y-axis scales

##### Step 6: Arrange the two plots side by side using patchwork
# Explicitly control the layout with patchwork

# Arrange the Map and Time Series Side by Side
grid.arrange(
  map_plot_F, time_series_plot_F,
  ncol = 2,  # Side-by-side layout
  widths = c(1, 2)  # Adjust the relative width of the plots
)
```

## Assessing the change in frequency of 100-year drought events (Extremely severe drought)


```{r calculate return periods all regions 100yr, echo=FALSE, message=FALSE, eval=FALSE}
use_rp <- 100    # return period of two years
nyears <- 30   # bin width

# From https://geco-bern.github.io/cwd/articles/cwd_example.html: 
# calculate return period as a function of the CWD extreme. Using the two 
# coefficients of the fitted distribution as arguments
calc_return_period <- function(x, loc, scale){
  1 / (1 - exp(-exp(-(x-loc)/scale)))
}

extract_loc <- function(mod){
  loc <- mod$results$par[ "location" ]
  if (!is.null(loc)){
    return(loc)
  } else {
    return(NA)
  }
}

extract_scale <- function(mod){
  scale <- mod$results$par[ "scale" ]
  if (!is.null(scale)){
    return(scale)
  } else {
    return(NA)
  }
}


# Initialize a list to store results for all regions
all_regions_results <- list()

# Loop through each region in regional_results
for (region in names(regional_results)) { #swap european_regions for regional_results for all regions
  # Extract the result array for the current region
  result_array_region <- regional_results[[region]]

  # Calculate magnitude of event with RP = X in reference period
  # Calculate the baseline 2-year return level using the first 30 years
  baseline <- as.vector(result_array_region[(1:nyears),])
  fit_ref <- extRemes::fevd(baseline, type = "Gumbel", method = "MLE", units = "years")
  cwd_ref <- extRemes::return.level(fit_ref, return.period = use_rp)

  # initialise
  rp_window <- rep(NA, nrow(result_array_region) - nyears + 1)

  for (window_start in 1:(nrow(result_array_region) - nyears + 1)){

    # Extract data for the current window
    window_data <- result_array_region[window_start:(window_start + nyears - 1), ]
  
    # Flatten the matrix into a single vector
    window_data <- as.vector(window_data)
  
    # Fit Gumbel distribution to the window data
    fit_window <- fevd(window_data, type = "Gumbel")

	  # determine return period of cwd_ref based on new fit (How much more/less probably is an event that corresponded to an X-yearly event in the reference period?)
	  rp_window[window_start] <- calc_return_period(cwd_ref, extract_loc(fit_window), extract_scale(fit_window))

  }
  # Create a dataframe for the current region
  time_info <- seq(from = as.numeric(1420), to = as.numeric(2009))  # Replace with actual time if available
  region_df <- data.frame(
    time = time_info[15:575],
    RP = rp_window,
    region = region
  )
  
  # Store the region's dataframe in the results list
  all_regions_results[[region]] <- region_df
}
  
# Combine all region results into a single dataframe
combined_results <- do.call(rbind, all_regions_results)

# Save or process the combined dataframe
# Example: Save to a CSV file
write.csv(combined_results, "~/cwd_global/data/100yr_return_periods_regions_duration.csv", row.names = FALSE)
```

```{r timeseries and map plots for each region 100yr, echo=FALSE, message=FALSE, warning=FALSE}
###### 1. Read in return period data
# Load the CSV files for each window size
#df_50yr<- read.csv("~/cwd_global/data/100yr_effective_return_periods_regions_50.csv")  ###RP is called effective_return_period in this file
#df_150yr <- read.csv("~/cwd_global/data/100yr_effective_return_periods_regions_150.csv")
combined_df <- read.csv("~/cwd_global/data/100yr_return_periods_regions_duration.csv")

# Add a new column to identify window size for each dataframe
combined_df$window_size <- "30yr"
# df_150yr$window_size <- "150yr"
# df_300yr$window_size <- "300yr"

# Combine the three dataframes into one
#combined_df <- bind_rows(df_50yr, df_150yr, df_300yr)

####################################### EUROPE #####################################
##### Step 2: Filter European regions for the map and timeseries
# Filter regions for Europe
selected_continent <- "Europe"
sel_regions <- continent_mapping[[selected_continent]]

# Filter combined data for timeseries 
combined_df_sel <- combined_df %>% filter(region %in% sel_regions)

# Filter spatial data for map
sel_regions_sf <- refregions_sf %>% filter(continent %in% selected_continent)

# Define bounding box for Europe
bbox <- c(xmin = -30, xmax = 70, ymin = 25, ymax = 75)  # Approximate bounding box for Europe

#### Step 4: Create the map
map_plot <- ggplot() +
  geom_sf(data = land, fill = "lightgray", color = NA) +  # Fill land areas
  geom_sf(data = sel_regions_sf, aes(fill = continent), color = "black", alpha = 0.6) +  # Transparent overlay
  geom_sf_text(data = region_labels, aes(label = label), size = 3, color = "black", check_overlap = TRUE) +  # Add region names
  scale_fill_manual(values = continent_colors, name = "") +
  theme_classic() +
  labs(title = "IPCC Regions", ylabs="", xlabs="") +
  theme(
    plot.title = element_text(size = 14, face = "bold"),
    plot.subtitle = element_text(size = 12),
    legend.position = "bottom"
  ) +
  coord_sf(xlim = bbox[1:2], ylim = bbox[3:4], expand = FALSE)  # Crop the map to Europe

##### Step 5: Plot the time series data with faceting
time_series_plot <- ggplot(combined_df_sel, aes(x = time, y = RP, color = window_size)) +
  geom_line() +  # Plot lines for each region's return period
  geom_hline(yintercept = 100, linetype = "dashed", color = "black") +  # Add a reference line for 2-year return period
  labs(
    x = "Year",
    y = "Effective Return Period",
    title = "Frequency Change of 100-Year Events"
  ) +
  scale_color_manual(name = "Window Size", values = c("50yr" = "cadetblue", "150yr" = "chocolate1", "30yr" = "chartreuse3")) +
  theme_classic() +
  theme(
    legend.position = "top",
    plot.title = element_text(hjust = 0.5, face = "bold"),  # Center the title
    strip.text = element_text(size = 10),  # Size for facet labels
    strip.background = element_rect(fill = "pink")
  ) +
  facet_wrap(~region, scales = "free_y"
             )  # Facet by region with independent y-axis scales

##### Step 6: Arrange the two plots side by side using patchwork
# Explicitly control the layout with patchwork

# Arrange the Map and Time Series Side by Side
grid.arrange(
  map_plot, time_series_plot,
  ncol = 2,  # Side-by-side layout
  widths = c(1, 2)  # Adjust the relative width of the plots
)


######################################ASIA#######################################
##### Step 2: Filter Asian regions for the map and timeseries
# Filter regions for Asian
selected_continent <- "Asia"
sel_regions <- continent_mapping[[selected_continent]]

# Filter combined data for timeseries 
combined_df_sel <- combined_df %>% filter(region %in% sel_regions)

# Filter spatial data for map
sel_regions_sf <- refregions_sf %>% filter(continent %in% selected_continent)

# Define bounding box for Asia
bbox <- c(xmin = 30, xmax = 190, ymin = -20, ymax = 90)  # Approximate bounding box for Europe

#### Step 4: Create the map
map_plot_A <- ggplot() +
  geom_sf(data = land, fill = "lightgray", color = NA) +  # Fill land areas
  geom_sf(data = sel_regions_sf, aes(fill = continent), color = "black", alpha = 0.6) +  # Transparent overlay
  geom_sf_text(data = region_labels, aes(label = label), size = 3, color = "black", check_overlap = TRUE) +  # Add region names
  scale_fill_manual(values = continent_colors, name = "") +
  theme_classic() +
  labs(title = "IPCC Regions", ylabs="", xlabs="") +
  theme(
    plot.title = element_text(size = 14, face = "bold"),
    plot.subtitle = element_text(size = 12),
    legend.position = "bottom"
  ) +
  coord_sf(xlim = bbox[1:2], ylim = bbox[3:4], expand = FALSE)  # Crop the map to Asia

##### Step 5: Plot the time series data with faceting
time_series_plot_A <- ggplot(combined_df_sel, aes(x = time, y = RP, color = window_size)) +
  geom_line() +  # Plot lines for each region's return period
  geom_hline(yintercept = 100, linetype = "dashed", color = "black") +  # Add a reference line for 2-year return period
  labs(
    x = "Year",
    y = "Effective Return Period",
    title = "Frequency Change of 100-Year Events"
  ) +
  scale_color_manual(name = "Window Size", values = c("50yr" = "cadetblue", "150yr" = "chocolate1", "30yr" = "chartreuse3")) +
  theme_classic() +
  theme(
    legend.position = "top",
    plot.title = element_text(hjust = 0.5, face = "bold"),  # Center the title
    strip.text = element_text(size = 10),  # Size for facet labels
    strip.background = element_rect(fill = "orange")
  ) +
  facet_wrap(~region, scales = "free_y")  # Facet by region with independent y-axis scales

##### Step 6: Arrange the two plots side by side using patchwork
# Explicitly control the layout with patchwork

# Arrange the Map and Time Series Side by Side
grid.arrange(
  map_plot_A, time_series_plot_A,
  ncol = 2,  # Side-by-side layout
  widths = c(1, 2)  # Adjust the relative width of the plots
)


###################################### OCEANIA #######################################
##### Step 2: Filter Oceanian regions for the map and timeseries
# Filter regions for Oceania
selected_continent <- "Australia"
sel_regions <- continent_mapping[[selected_continent]]

# Filter combined data for timeseries 
combined_df_sel <- combined_df %>% filter(region %in% sel_regions)

# Filter spatial data for map
sel_regions_sf <- refregions_sf %>% filter(continent %in% selected_continent)

# Define bounding box for Oceania
bbox <- c(xmin = 100, xmax = 190, ymin = -60, ymax = 0)  # Approximate bounding box for Oceania

#### Step 4: Create the map
map_plot_B <- ggplot() +
  geom_sf(data = land, fill = "lightgray", color = NA) +  # Fill land areas
  geom_sf(data = sel_regions_sf, aes(fill = continent), color = "black", alpha = 0.6) +  # Transparent overlay
  geom_sf_text(data = region_labels, aes(label = label), size = 3, color = "black", check_overlap = TRUE) +  # Add region names
  scale_fill_manual(values = continent_colors, name = "") +
  theme_classic() +
  labs(title = "IPCC Regions", ylabs="", xlabs="") +
  theme(
    plot.title = element_text(size = 14, face = "bold"),
    plot.subtitle = element_text(size = 12),
    legend.position = "bottom"
  ) +
  coord_sf(xlim = bbox[1:2], ylim = bbox[3:4], expand = FALSE)  # Crop the map to Asia

##### Step 5: Plot the time series data with faceting
time_series_plot_B <- ggplot(combined_df_sel, aes(x = time, y = RP, color = window_size)) +
  geom_line() +  # Plot lines for each region's return period
  geom_hline(yintercept = 100, linetype = "dashed", color = "black") +  # Add a reference line for 2-year return period
  labs(
    x = "Year",
    y = "Effective Return Period",
    title = "Frequency Change of 100-Year Events"
  ) +
  scale_color_manual(name = "Window Size", values = c("50yr" = "cadetblue", "150yr" = "chocolate1", "30yr" = "chartreuse3")) +
  theme_classic() +
  theme(
    legend.position = "top",
    plot.title = element_text(hjust = 0.5, face = "bold"),  # Center the title
    strip.text = element_text(size = 10),  # Size for facet labels
    strip.background = element_rect(fill = "blue")
  ) +
  facet_wrap(~region, scales = "free_y")  # Facet by region with independent y-axis scales

##### Step 6: Arrange the two plots side by side using patchwork
# Explicitly control the layout with patchwork

# Arrange the Map and Time Series Side by Side
grid.arrange(
  map_plot_B, time_series_plot_B,
  ncol = 2,  # Side-by-side layout
  widths = c(1, 2)  # Adjust the relative width of the plots
)


###################################### AFRICA #######################################
##### Step 2: Filter African regions for the map and timeseries
# Filter regions for Africa
selected_continent <- "Africa"
sel_regions <- continent_mapping[[selected_continent]]

# Filter combined data for timeseries 
combined_df_sel <- combined_df %>% filter(region %in% sel_regions)

# Filter spatial data for map
sel_regions_sf <- refregions_sf %>% filter(continent %in% selected_continent)

# Define bounding box for Africa
bbox <- c(xmin = -30, xmax = 60, ymin = -40, ymax = 40)  # Approximate bounding box for Oceania

#### Step 4: Create the map
map_plot_C <- ggplot() +
  geom_sf(data = land, fill = "lightgray", color = NA) +  # Fill land areas
  geom_sf(data = sel_regions_sf, aes(fill = continent), color = "black", alpha = 0.6) +  # Transparent overlay
  geom_sf_text(data = region_labels, aes(label = label), size = 3, color = "black", check_overlap = TRUE) +  # Add region names
  scale_fill_manual(values = continent_colors, name = "") +
  theme_classic() +
  labs(title = "IPCC Regions", ylabs="", xlabs="") +
  theme(
    plot.title = element_text(size = 14, face = "bold"),
    plot.subtitle = element_text(size = 12),
    legend.position = "bottom"
  ) +
  coord_sf(xlim = bbox[1:2], ylim = bbox[3:4], expand = FALSE)  # Crop the map to Asia

##### Step 5: Plot the time series data with faceting
time_series_plot_C <- ggplot(combined_df_sel, aes(x = time, y = RP, color = window_size)) +
  geom_line() +  # Plot lines for each region's return period
  geom_hline(yintercept = 100, linetype = "dashed", color = "black") +  # Add a reference line for 2-year return period
  labs(
    x = "Year",
    y = "Effective Return Period",
    title = "Frequency Change of 100-Year Events"
  ) +
  scale_color_manual(name = "Window Size", values = c("50yr" = "cadetblue", "150yr" = "chocolate1", "30yr" = "chartreuse3")) +
  theme_classic() +
  theme(
    legend.position = "top",
    plot.title = element_text(hjust = 0.5, face = "bold"),  # Center the title
    strip.text = element_text(size = 10),  # Size for facet labels
    strip.background = element_rect(fill = "purple")
  ) +
  facet_wrap(~region, scales = "free_y")  # Facet by region with independent y-axis scales

##### Step 6: Arrange the two plots side by side using patchwork
# Explicitly control the layout with patchwork

# Arrange the Map and Time Series Side by Side
grid.arrange(
  map_plot_C, time_series_plot_C,
  ncol = 2,  # Side-by-side layout
  widths = c(1, 2)  # Adjust the relative width of the plots
)


###################################### N AMERICA #######################################
##### Step 2: Filter N AMERICA regions for the map and timeseries
# Filter regions for N America
selected_continent <- "North America"
sel_regions <- continent_mapping[[selected_continent]]

# Filter combined data for timeseries 
combined_df_sel <- combined_df %>% filter(region %in% sel_regions)

# Filter spatial data for map
sel_regions_sf <- refregions_sf %>% filter(continent %in% selected_continent)

# Define bounding box for N America
bbox <- c(xmin = -180, xmax = -10, ymin = 20, ymax = 90)  # Approximate bounding box for Oceania

#### Step 4: Create the map
map_plot_D <- ggplot() +
  geom_sf(data = land, fill = "lightgray", color = NA) +  # Fill land areas
  geom_sf(data = sel_regions_sf, aes(fill = continent), color = "black", alpha = 0.6) +  # Transparent overlay
  geom_sf_text(data = region_labels, aes(label = label), size = 3, color = "black", check_overlap = TRUE) +  # Add region names
  scale_fill_manual(values = continent_colors, name = "") +
  theme_classic() +
  labs(title = "IPCC Regions", ylabs="", xlabs="") +
  theme(
    plot.title = element_text(size = 14, face = "bold"),
    plot.subtitle = element_text(size = 12),
    legend.position = "bottom"
  ) +
  coord_sf(xlim = bbox[1:2], ylim = bbox[3:4], expand = FALSE)  # Crop the map to Asia

##### Step 5: Plot the time series data with faceting
time_series_plot_D <- ggplot(combined_df_sel, aes(x = time, y = RP, color = window_size)) +
  geom_line() +  # Plot lines for each region's return period
  geom_hline(yintercept = 100, linetype = "dashed", color = "black") +  # Add a reference line for 2-year return period
  labs(
    x = "Year",
    y = "Effective Return Period",
    title = "Frequency Change of 100-Year Events"
  ) +
  scale_color_manual(name = "Window Size", values = c("50yr" = "cadetblue", "150yr" = "chocolate1", "30yr" = "chartreuse3")) +
  theme_classic() +
  theme(
    legend.position = "top",
    plot.title = element_text(hjust = 0.5, face = "bold"),  # Center the title
    strip.text = element_text(size = 10),  # Size for facet labels
    strip.background = element_rect(fill = "lightgreen")
  ) +
  facet_wrap(~region, scales = "free_y")  # Facet by region with independent y-axis scales

##### Step 6: Arrange the two plots side by side using patchwork
# Explicitly control the layout with patchwork

# Arrange the Map and Time Series Side by Side
grid.arrange(
  map_plot_D, time_series_plot_D,
  ncol = 2,  # Side-by-side layout
  widths = c(1, 2)  # Adjust the relative width of the plots
)


###################################### C AMERICA #######################################
##### Step 2: Filter C AMERICA regions for the map and timeseries
# Filter regions for C America
selected_continent <- "Central America"
sel_regions <- continent_mapping[[selected_continent]]

# Filter combined data for timeseries 
combined_df_sel <- combined_df %>% filter(region %in% sel_regions)

# Filter spatial data for map
sel_regions_sf <- refregions_sf %>% filter(continent %in% selected_continent)

# Define bounding box for C America
bbox <- c(xmin = -130, xmax = -50, ymin = 0, ymax = 40)  # Approximate bounding box for Oceania

#### Step 4: Create the map
map_plot_E <- ggplot() +
  geom_sf(data = land, fill = "lightgray", color = NA) +  # Fill land areas
  geom_sf(data = sel_regions_sf, aes(fill = continent), color = "black", alpha = 0.6) +  # Transparent overlay
  geom_sf_text(data = region_labels, aes(label = label), size = 3, color = "black", check_overlap = TRUE) +  # Add region names
  scale_fill_manual(values = continent_colors, name = "") +
  theme_classic() +
  labs(title = "IPCC Regions", ylabs="", xlabs="") +
  theme(
    plot.title = element_text(size = 14, face = "bold"),
    plot.subtitle = element_text(size = 12),
    legend.position = "bottom"
  ) +
  coord_sf(xlim = bbox[1:2], ylim = bbox[3:4], expand = FALSE)  # Crop the map to Asia

##### Step 5: Plot the time series data with faceting
time_series_plot_E <- ggplot(combined_df_sel, aes(x = time, y = RP, color = window_size)) +
  geom_line() +  # Plot lines for each region's return period
  geom_hline(yintercept = 100, linetype = "dashed", color = "black") +  # Add a reference line for 2-year return period
  labs(
    x = "Year",
    y = "Effective Return Period",
    title = "Frequency Change of 100-Year Events"
  ) +
  scale_color_manual(name = "Window Size", values = c("50yr" = "cadetblue", "150yr" = "chocolate1", "30yr" = "chartreuse3")) +
  theme_classic() +
  theme(
    legend.position = "top",
    plot.title = element_text(hjust = 0.5, face = "bold"),  # Center the title
    strip.text = element_text(size = 10),  # Size for facet labels
    strip.background = element_rect(fill = "lightblue")
  ) +
  facet_wrap(~region, scales = "free_y")  # Facet by region with independent y-axis scales

##### Step 6: Arrange the two plots side by side using patchwork
# Explicitly control the layout with patchwork

# Arrange the Map and Time Series Side by Side
grid.arrange(
  map_plot_E, time_series_plot_E,
  ncol = 2,  # Side-by-side layout
  widths = c(1, 2)  # Adjust the relative width of the plots
)


###################################### S AMERICA #######################################
##### Step 2: Filter S AMERICA regions for the map and timeseries
# Filter regions for S America
selected_continent <- "South America"
sel_regions <- continent_mapping[[selected_continent]]

# Filter combined data for timeseries 
combined_df_sel <- combined_df %>% filter(region %in% sel_regions)

# Filter spatial data for map
sel_regions_sf <- refregions_sf %>% filter(continent %in% selected_continent)

# Define bounding box for S America
bbox <- c(xmin = -90, xmax = -30, ymin = -60, ymax = 15)  # Approximate bounding box for Oceania

#### Step 4: Create the map
map_plot_F <- ggplot() +
  geom_sf(data = land, fill = "lightgray", color = NA) +  # Fill land areas
  geom_sf(data = sel_regions_sf, aes(fill = continent), color = "black", alpha = 0.6) +  # Transparent overlay
  geom_sf_text(data = region_labels, aes(label = label), size = 3, color = "black", check_overlap = TRUE) +  # Add region names
  scale_fill_manual(values = continent_colors, name = "") +
  theme_classic() +
  labs(title = "IPCC Regions", ylabs="", xlabs="") +
  theme(
    plot.title = element_text(size = 14, face = "bold"),
    plot.subtitle = element_text(size = 12),
    legend.position = "bottom"
  ) +
  coord_sf(xlim = bbox[1:2], ylim = bbox[3:4], expand = FALSE)  # Crop the map to South America

##### Step 5: Plot the time series data with faceting
time_series_plot_F <- ggplot(combined_df_sel, aes(x = time, y = RP, color = window_size)) +
  geom_line() +  # Plot lines for each region's return period
  geom_hline(yintercept = 100, linetype = "dashed", color = "black") +  # Add a reference line for 100-year return period
  labs(
    x = "Year",
    y = "Effective Return Period",
    title = "Frequency Change of 100-Year Events"
  ) +
  scale_color_manual(name = "Window Size", values = c("50yr" = "cadetblue", "150yr" = "chocolate1", "30yr" = "chartreuse3")) +
  theme_classic() +
  theme(
    legend.position = "top",
    plot.title = element_text(hjust = 0.5, face = "bold"),  # Center the title
    strip.text = element_text(size = 10),  # Size for facet labels
    strip.background = element_rect(fill = "yellow")
  ) +
  facet_wrap(~region, scales = "free_y")  # Facet by region with independent y-axis scales

##### Step 6: Arrange the two plots side by side using patchwork
# Explicitly control the layout with patchwork

# Arrange the Map and Time Series Side by Side
grid.arrange(
  map_plot_F, time_series_plot_F,
  ncol = 2,  # Side-by-side layout
  widths = c(1, 2)  # Adjust the relative width of the plots
)
```
