---
title: "Extreme Value Analysis PCWD"
author: "Patricia Helpap"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r message=FALSE}
library(readr)
library(dplyr)
library(here)
library(lubridate)
library(patchwork)
library(extRemes)
library(ggplot2)
library(cwd)
library(ncdf4)
library(reshape2)
library(ggpubr)
library(maps)
library(raster)
library(rnaturalearth)
library(sf)
```

Load reference regions and coastlines:
```{r}
load("/storage/homefs/ph23v078/Reference_regions/IPCC-WGI-reference-regions-v4_R.rda", verbose = TRUE)

#simplify this object by converting it to a SpatialPolygons class object (i.e., only the polygons are retained and their attributes discarded):
refregions <- as(IPCC_WGI_reference_regions_v4, "SpatialPolygons")

temp.dir <- tempdir()
unzip("/storage/homefs/ph23v078/Reference_regions/ne_110m_coastline.zip", exdir = temp.dir)
coastLines <- readOGR(dsn = temp.dir, layer = "ne_110m_coastline")

```

```{r}
#aggregate EM for region i.e. 2 for loops, 1 looping over EMs, second looping over region, aggregating into one file


###############################
#e.g. loop for EMs: ### append data i.e. get rid of time dimension and just append to exisiting data
# Load necessary libraries
library(ncdf4)

# Define the base path
path <- "/storage/research/giub_geco/data_2/scratch/phelpap/ModESim/"

# List all the directories within the base path
folders <- list.files(path, full.names = TRUE)

# Identify the target files
target_files <- file.path(folders, "04_result_1850/PCWD_ANNMAX.nc")
target_files <- target_files[file.exists(target_files)]  # Ensure only existing files are included


# Initialize an array to store the extended data
# Extract dimensions from the first file to initialize the array
nc <- nc_open(target_files[1])
dim_x <- dim(ncvar_get(nc, "pcwd_annmax"))[1]
dim_y <- dim(ncvar_get(nc, "pcwd_annmax"))[2]
dim_z <- dim(ncvar_get(nc, "pcwd_annmax"))[3]
nc_close(nc)

# Prepare an array to store the extended data
extended_data <- array(NA, dim = c(dim_x, dim_y, dim_z * length(target_files)))

# Loop through all the target files to extract the data and append along the third dimension
current_index <- 1
for (file in target_files) {
  # Open the NetCDF file
  nc <- nc_open(file)
  
  # Extract the data variable
  data <- ncvar_get(nc, "pcwd_annmax")  # Adjust "pcwd_annmax" to your variable name
  
  # Determine the slice of the extended array to update
  slice_indices <- current_index:(current_index + dim(data)[3] - 1)
  
  # Append the data to the extended array
  extended_data[,,slice_indices] <- data
  
  # Update the current index
  current_index <- current_index + dim(data)[3]
  
  # Close the file
  nc_close(nc)
}

# Output the structure of the extended data
print(dim(extended_data))  # Check dimensions (x, y, extended z)

# Optionally, inspect a slice of the extended data for verification
print(extended_data[,,1:10])  # Inspect the first 10 slices


########### integrate loop for regions: (do for all based on list with all regions)

MED <- refregions["MED"]
NEU <- refregions["NEU"]
WCE <- refregions["WCE"]


#should end with aggregated object containing all info for region i.e. 160 values for second period region x20 for all EMs
```

