---
title: "Fluxnet Comparison"
author: "Patricia Gribi"
date: "2024-06-26"
output: html_document
---

# Data Info

https://fluxnet.org/data/fluxnet2015-dataset/subset-data-product/

site info: https://fluxnet.org/sites/siteinfo/DE-Tha 

MDS: gapfilled using MDS method


# Preparing Fluxnet data

```{r}

library(dplyr)
library(ggplot2)

# data reading
fluxnet <- read.csv(paste0(here::here(),"/data-raw/FLX_DE-Tha_FLUXDATAKIT_FULLSET_DD_1996_2020_2-3.csv"), header=TRUE)


# variable selection
fluxnet <- fluxnet |>
  dplyr::select(
  TIMESTAMP,
  P_F, # precipitation (mm d-1)
  LE_F_MDS, # latent heat flux (W m-2)
  TA_F_MDS, # temperature (°C)
  NETRAD) # net radiation (W m-2)

```

units are correct, Lat, Lon:	50.9626, 13.5651 

used lon 11 from cmip data and lat 50/51.


## PET and ET Calculation


```{r}

elevation <- 385

source(paste0(here::here(), "/R/calc_patm.R"))
patm <- calc_patm(elevation)


# ET -----------------------------------

## Convert latent heat flux (W/m2) to evapotranspiration in mass units (mm/d).

le_to_et <- function(le, tc, patm){
  1000 * 60 * 60 * 24 * le / (cwd::calc_enthalpy_vap(tc) * cwd::calc_density_h2o(tc, patm)) 
}

fluxnet <- fluxnet |>
  mutate(et = le_to_et(LE_F_MDS, TA_F_MDS, patm))


# PET ----------------------------------

## apply pet() function
  fluxnet <- fluxnet |>
    mutate(pet = 60 * 60 * 24 * cwd::pet(NETRAD, TA_F_MDS, patm))

```


# Reading CMIP6 data

```{r}

# data reading
cwd <- readRDS(paste0(here::here(),"/data-raw/extracted_vars_fluxnetcomp_cwd.rds"))
pcwd <- readRDS(paste0(here::here(),"/data-raw/extracted_vars_fluxnetcomp_pcwd.rds"))

cmip6 <- cwd |>
  left_join(pcwd, by = join_by(lon, lat, time, pr, tas))


# unit conversions
## evapotranspiration
cmip6$evspsbl <- cmip6$evspsbl * 86400 # conversion to mm day-1

## precipitation
cmip6$pr <- cmip6$pr * 86400 # conversion to mm day-1

## temperature
cmip6$tas <- cmip6$tas - 273.15 # conversion to °C


# time-range adjustment (2015-2020)
cmip6 <- cmip6 |>
  mutate(year = lubridate::year(time))|>
  filter((year >= 2015) & (year <= 2020))


# pet
## apply pet() function
patm_cmip6 <- calc_patm(cmip6$elevation[1])

cmip6 <- cmip6 |>
  mutate(pet = 60 * 60 * 24 * cwd::pet(net_radiation, tas, patm_cmip6))


```


## Plot 


```{r}
#tas = mean(TA_F_MDS), netrad = mean(NETRAD)

# data preparation
year_fluxnet <- fluxnet |>
  mutate(year = lubridate::year(TIMESTAMP)) |>
  group_by(year) |>
  filter(year >= 2015) |> 
  summarise(et = mean(et), pet = mean(pet), prec = mean(P_F))

year_cmip6 <- cmip6 |>
  mutate(year = lubridate::year(time)) |>
  group_by(year) |>
  summarise(et = mean(evspsbl), pet = mean(pet), prec = mean(pr))


# plot
year_fluxnet |>
  tidyr::pivot_longer(cols = c(et, pet, prec), names_to = "Flux") |> 
  ggplot(aes(x = year, y = value, color = Flux)) +
  geom_line() +
  ggtitle("Mean Annual Fluxes Fluxnet")+
  labs(y = "Flux (mm/yr)")

year_cmip6 |>
  tidyr::pivot_longer(cols = c(et, pet, prec), names_to = "Flux") |> 
  ggplot(aes(x = year, y = value, color = Flux)) +
  geom_line() +
  ggtitle("Mean Annual Fluxes CMIP6")+
  labs(y = "Flux (mm/yr)")


```



# Compare the deficits

```{r}

# read cmip6 deficit data

deficit_cwd <- readRDS("/data_1/CMIP6/tidy/cwd/cwd_11.rds")
deficit_pcwd <- readRDS("/data_1/CMIP6/tidy/pcwd/pcwd_11.rds")

deficit_cwd <- deficit_cwd |> tidyr::unnest(data)
deficit_pcwd <- deficit_pcwd |> tidyr::unnest(data)


deficit_cmip6 <- deficit_pcwd |>
  rename(deficit_pcwd = deficit)|>
  left_join(deficit_cwd, by = join_by(lon, lat, time))


# extract nearest latitude 50.9 
start <- 50
end <- 51
deficit_cmip6 <- deficit_cmip6[(deficit_cmip6$lat >= start) & (deficit_cmip6$lat <= end), ]


# time-range adjustment (2015-2020)
deficit_cmip6 <- deficit_cmip6 |>
  mutate(year = lubridate::year(time))|>
  filter((year >= 2015) & (year <= 2020))|>
  group_by(year) |>
  summarise(deficit_cwd = mean(deficit), deficit_pcwd = mean(deficit_pcwd)) 

  
# get cwd of fluxnet data
## snow simulation
fluxnet <- fluxnet |>
  mutate(precipitation = ifelse(TA_F_MDS < 0, 0, P_F),
         snow = ifelse(TA_F_MDS < 0, P_F, 0)) |>
  cwd::simulate_snow(varnam_prec = "precipitation", varnam_snow = "snow", varnam_temp = "TA_F_MDS")


fluxnet <- fluxnet |>
  mutate(wbal = liquid_to_soil - et)


# cwd
## calculate cumulative water deficit
out_cwd_fluxnet <- cwd::cwd(fluxnet,
               varname_wbal = "wbal",
               varname_date = "TIMESTAMP",
               thresh_terminate = 0.0,
               thresh_drop = 0.0)

out_cwd_fluxnet$inst <- out_cwd_fluxnet$inst |>
  filter(len >= 20)

out_cwd_fluxnet$df <- out_cwd_fluxnet$df |>
  select(TIMESTAMP, deficit)

full_data <- out_cwd_fluxnet$df
  
```




```{r}

# data preparation
full_data <- full_data |>
  mutate(year = lubridate::year(TIMESTAMP)) |>
  group_by(year) |>
  filter(year >= 2015) |> 
  summarise(deficit_fluxnet = mean(deficit))

# join cmip6-deficit
full_data <- full_data |>
  left_join(deficit_cmip6, by = join_by(year))


# plot
full_data |>
  tidyr::pivot_longer(cols = c(deficit_fluxnet, deficit_cwd, deficit_pcwd), names_to = "Flux") |> 
  ggplot(aes(x = year, y = value, color = Flux)) +
  geom_line() +
  ggtitle("Comparison Mean Annual Fluxes ")+
  labs(y = "Flux (mm/yr)")


deficit_cmip6 |>
  tidyr::pivot_longer(cols = c(deficit_cwd, deficit_pcwd), names_to = "Flux") |> 
  ggplot(aes(x = year, y = value, color = Flux)) +
  geom_line() +
  ggtitle("Comparison Mean Annual Fluxes ")+
  labs(y = "Flux (mm/yr)")





```

